type Mutation {
  refreshToken(refreshToken: String!): SignInResponse!
  signIn(input: UserInput!): SignInResponse!
  signOut(refreshToken: String!): SignOutResponse!
  signUp(input: UserInput!): SignUpResponse!
}

type Query {
  currentUser: SignUpResponse!
}

type SignInResponse {
  accessToken: String!
  refreshToken: String!
  userId: String!
}

type SignOutResponse {
  message: String!
}

type SignUpResponse {
  id: ID!
  username: String!
}

input UserInput {
  password: String!
  username: String!
}