type Mutation {
  signIn(input: UserInput!): SignInResponse!
  signUp(input: UserInput!): SignUpResponse!
}

type Query {
  currentUser: SignUpResponse!
}

type SignInResponse {
  accessToken: String!
  refreshToken: String!
  userId: String!
}

type SignUpResponse {
  id: ID!
  username: String!
}

input UserInput {
  password: String!
  username: String!
}